body_part = input('enter the name of a body part ')
verb = input('enter a verb ')
adjective = input('enter an adjective ')
noun = input('enter a noun ')
beverage = input('enter the name of a beverage ')
clothing = input('enter the name of an article of clothing ')
weather = input('enter a type of weather ')
weapon = input('enter the name of a weapon ')
print('The Weather, By Pond\n')
print('He sold out both his ' + body_part)
print('Yet ' + verb + ' her face')
print('Her thighs in lace')
print('Oh, why such waste?\n')
print('Ghost are only ' + adjective + ' space')
print('Ancestors, no ' + noun)
print('No place, no mark')
print('Just voices, in the dark\n')
print('The floor is covered in ' + beverage)
print('The ' + clothing + ' and the blood')
print('And all the sudden rain')
print('Man, you should\'ve seen those cops baptize')
print('The worse case scenario, survival game\n')
print('He sold out both of his ' + body_part)
print('Yet ' + verb + ' her face')
print('Her thighs in lace')
print('Oh, why such waste?\n')
print('The floor is covered in ' + beverage)
print('The ' + clothing + ' and the blood')
print('And all the sudden rain')
print('Man, you should\'ve seen those cops' + weapon)
print('The worse case scenario, survival game')
