person = input("Enter the name of a person:")
occupation = input("Enter an occupation:")
occupation2 = input("Enter a different occupation:")
country = input("Enter a country:")
time = input ("Enter a period of time:")
emotion = input("Enter an emotion:")
animal = input("Enter the name of an animal (plural):")
noun = input("Enter a noun (plural):")
print("\n")
print("Heroes, by David Bowie")
print(person + " will be a " + occupation)
print("And you, you will be a " + occupation2)
print("Though nothing will drive " + country + " away")
print("We can beat them, just for one " + time)
print("We can be heroes, just for one " + time + "\n")
print("And you, you can be " + emotion)
print("And I, I'll drink all the time")
print("'Cause we're " + animal + ", and that is a fact")
print("Yes we're " + animal + ", and that is that")
print("Though nothing will keep us together")
print("We could steal " + noun + ", just for one day")
print("We can be Heroes, for ever and ever")
print("What d'you say?\n")
