print("Heroes, by David Bowie")
print("I, I will be king")
print("And you, you will be queen")
print("Though nothing will drive them away")
print("We can beat them, just for one day")
print("We can be heroes, just for one day\n")

print("And you, you can be mean")
print("And I, I'll drink all the time")
print("'Cause we're lovers, and that is a fact")
print("Yes we're lovers, and that is that")
print("Though nothing will keep us together")
print("We could steal time, just for one day")
print("We can be Heroes, for ever and ever")
print("What d'you say?\n")
